name: apptentive_flutter_example
description: Demonstrates how to use the apptentive_flutter plugin.
publish_to: 'none'

environment:
  sdk: '>=2.15.0 <3.0.0'

dependencies:
  alkami_core_dependencies: 
    hosted: https://dart.cloudsmith.io/alkami/flutter/
    version: ^2.1.0

  apptentive_flutter:
    path: ../

  flutter:
    sdk: flutter

  firebase_messaging: ^14.0.3

# dependency_overrides:
#   alkami_core_dependencies:
#     path: ../../flutter_platform/packages/alkami_core_dependencies

dev_dependencies:
  # alkami_core_dev_dependencies:
  #   path: ../../flutter_platform/packages/alkami_core_dev_dependencies
  alkami_core_dev_dependencies: 
    hosted: https://dart.cloudsmith.io/alkami/flutter/
    version: ^2.1.0

flutter:
  uses-material-design: true
