name: apptentive_flutter_example
description: Demonstrates how to use the apptentive_flutter plugin.
publish_to: 'none'

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  apptentive_flutter:
    path: ../

  cupertino_icons: ^1.0.2
  firebase_messaging: ^14.3.0
  firebase_core: ^2.9.0
  fluttertoast: ^8.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
