name: apptentive_flutter
description: Apptentive SDK for Flutter
version: 6.2.0
repository: https://github.com/apptentive/apptentive-flutter
issue_tracker: https://github.com/apptentive/apptentive-flutter/issues
documentation: https://learn.apptentive.com/knowledge-base/apptentive-sdk-flutter-plugin-guide/
publish_to: https://dart.cloudsmith.io/alkami/flutter/

environment:
  sdk: '>=2.15.0 <3.0.0'
  flutter: ">=2.10.0"

dependencies:
  alkami_core_dependencies: 
    hosted: https://dart.cloudsmith.io/alkami/flutter/
    version: ^2.1.0

dev_dependencies:
  alkami_core_dev_dependencies: 
    hosted: https://dart.cloudsmith.io/alkami/flutter/
    version: ^2.1.0

  mplat_pr_tools: 
    hosted: https://dart.cloudsmith.io/alkami/flutter/
    version: ^2.1.0

flutter:
  plugin:
    platforms:
      android:
        package: com.apptentive.apptentive_flutter
        pluginClass: ApptentiveFlutterPlugin
      ios:
        pluginClass: ApptentiveFlutterPlugin
